name: MATSYA_ANDROID_CI_v2
on:
  push:
    branches: [ cicdTests ]
  pull_request:
    branches: [ cicdTests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
 
      - name: Build with Gradle
        run: ./gradlew build

