name: MATSYA_ANDROID_CI_v2
on:
  push:
    branches: [ cicdTests ]
  pull_request:
    branches: [ cicdTests ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '11' ]
    name: Java ${{ matrix.Java }} (${{ matrix.distribution }}) sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
 
      - name: Build with Gradle
        run: ./gradlew build
