name: MATSYA_ANDROID_CI
on:
  push:
    branches: [Anshul]
  pull_request:
    branches: [Anshul]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set Up JDK
      uses: action/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Run Tests
      run: ./gradlew test
    
    - name: Build Project
      run: ./gradlew assemble
